const base = import.meta.env.BASE_URL;
export const IMG = {
  mookAndMush:         `${base}images/MookAndMush.jpeg`,
  bayHouse:            `${base}images/BayHouse.jpeg`,
  charSheet:           `${base}images/Mook_character_sheet1.jpeg`,
  tvDogPoses:          `${base}images/TVdogposesheet.jpeg`,
  dogSculptures:       `${base}images/DogSculptures.jpg`,
  needleFelt:          `${base}images/NeedleFelt.jpg`,
  needleFelt2:         `${base}images/NeedleFlet2.jpg`,
  animation1:          `${base}images/Animation1.jpg`,
  abstractCoder:       `${base}images/abstract-coder.png`,
  texturedChild:       `${base}images/textured-child.png`,
  otisAbstract:        `${base}images/otis-abstract.png`,
  tvboy:               `${base}images/tvboy.png`,
  abstractBonsai:      `${base}images/abstract-bonsai.png`,
  dualFaces:           `${base}images/dual-faces.png`,
  abstractAstronaut:   `${base}images/abstract-astronaut.png`,
  doodle1:             `${base}images/doodle1.jpg`,
  dudemoon:            `${base}images/dudemoon.jpg`,
  noodles13:           `${base}images/noodles13.jpg`,
  blurArt:             `${base}images/blur-art.jpg`,
  gigabyteArt:         `${base}images/gigabyte-art.png`,
  tvdogSidekick2025:   `${base}images/tvdog-sidekick-2025.png`,
  headshot:            `${base}images/headshot.jpg`,
  mowersvilleBikes:    `${base}images/mowersville-bikes.png`,
  mowersvilleSkate:    `${base}images/mowersville-skatepark.png`,
  mowersvilleClass:    `${base}images/mowersville-classroom.png`,
  mowersvilleTown:     `${base}images/mowersville-town.png`,
  mowersvilleArtRoom:  `${base}images/mowersville-artroom.png`,
  mowersvilleSoccer:   `${base}images/mowersville-soccer.png`,
  mookNightwalk:       `${base}images/mook-nightwalk.png`,
  mookClassic:         `${base}images/mook-classic.png`,
};
